### ISSUE TITLE
Interaction

### ISSUE THREAD

**Issue by DixonR19** [QuantumTekSupport/QuantumDialogue#1]
Hi, your asset is very light, and it helps a lot. I'm not very experienced, and I don't know how to attach a Handler to an object so that player approach it, and only after that the dialog starts.

**Comment by QuantumTekSupport** [comment]
Here's a potential solution that I hope can help you:
If you constantly check in an Update method the distance between your player and the object you want, then if that Vector3.Distance is less than a certain value, you can show UI for the dialogue.

**Comment by DixonR19** [comment]
I need the window to open and play the text when the button is clicked. I have code for interactive, but when I try to use my own strings in your script, a large number of errors occur, even when I try to fix everything

**Comment by QuantumTekSupport** [comment]
Could you give a code example, please?

**Comment by DixonR19** [comment]
The script only helps with one message. That's why I'm looking for a dialog system, because my game will be more about dialogs.

'using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class Interactable : MonoBehaviour
{
    // Start is called before the first frame update
    public GameObject dialogBox;
    public TMPro.TextMeshProUGUI dialogText;
    [SerializeField] public string dialog;
    [SerializeField] public bool playerInRange;

    public Button bat;
    public Button brats;
    void Start()
    {
        dialogBox.SetActive(false);
        Button btn = bat.GetComponent<Button>();
        btn.onClick.AddListener(OnAbuttonDown);
        Button btnn = brats.GetComponent<Button>();
        btnn.onClick.AddListener(onScreenButtonDown);
        brats.gameObject.SetActive(false);
    }

    // Update is called once per frame
    void Update()
    {
    }
    public virtual void OnTriggerEnter2D(Collider2D other)
    {
        if (other.CompareTag("Player"))
        {
            playerInRange = true;
           
        }
    }
    public virtual void OnTriggerExit2D(Collider2D other)
    {
        if (other.CompareTag("Player"))
        {
            playerInRange = false;
         
            dialogBox.SetActive(false);
        }
    }

    public void OnAbuttonDown()
    {
        if (playerInRange == true)
        {
            if (dialogBox.activeInHierarchy)
            {
                dialogBox.SetActive(false);
            }
            else
            {
                dialogBox.SetActive(true);
                dialogText.text = dialog;
                brats.gameObject.SetActive(true);
            }
        }
    }
  public void onScreenButtonDown()
    { if (dialogBox != null)
        {
            if (dialogBox.activeInHierarchy)
            {
                
                
                dialogBox.SetActive(false);
                
            }
            else
            {
                brats.gameObject.SetActive(false);
            }
           
        }

    } 

} '

**Comment by QuantumTekSupport** [comment]
Are you wanting help with implementing my system into that?

**Comment by DixonR19** [comment]
I would be happy if you helped, I don't like this code very much, I just need help to trigger when the button is pressed and if the character is in the trigger

**Comment by QuantumTekSupport** [comment]
It looks to me like your code achieves this, but without my system. If you want to add in Quantum Dialogue, you'll need a reference to a `QD_DialogueHandler`. For this example I will name that variable `dialogueHandler`.

The first step would be to call `dialogueHandler.SetConversation("conversation name")` in the `Start` method, assuming "conversation name" is the name of your conversation in your `QD_Dialogue` asset.

When the button is pressed and the player is in range, you can say:
```
var currentMessageInfo = dialogueHandler.NextMessage();
if (the dialogue box is open)
{
    if (currentMessageInfo.NextID == -1)
    {
        // There is no next message, close the dialogue box
    }
    else
    {
        QD_Message currentMessage = dialogueHandler.GetMessage();
        // Set the dialogue text to currentMessage.MessageText
    }
}
else {
    QD_Message currentMessage = dialogueHandler.GetMessage();
    // Set the dialogue text to currentMessage.MessageText
    // Open the dialogue box
}
```

I hope this helps!

**Comment by DixonR19** [comment]
ok, thanks
