### ISSUE TITLE
Can't assign multiple inputs to message in Dialogue Editor

### ISSUE THREAD

**Issue by Vahv1** [QuantumTekSupport/QuantumDialogue#2]
Hello,

Is it a bug that multiple messages or choices cannot lead to same message in the Dialogue Editor? Or am I just trying to do it wrong because I can only attach one? Because through editing data fields in the same Dialogue it is possible, like in [this picture](https://i.imgur.com/pgf4COs.png) multiple choices lead to message 14 and it works. And it seems that after assigning the choices in the data fields like this, _then_ it is possible to connect them also in the Dialogue Editor.

Would be great if this could all be done in the Dialogue editor!

**Comment by QuantumTekSupport** [comment]
You should be able to assign multiple messages or choices leading to the same message, provided that the Knob used in the Input for your message or choice node AllowsMultipleConnections.

**Comment by QuantumTekSupport** [comment]
In the Editor/Scripts/QD_MessageNode.cs you can change the constructor with the following in order to allow multiple connections in the node editor.
```
Inputs = new List<QD_Knob>
{
    new QD_Knob(0, "Speaker", QD_KnobType.Input, 7.5f, false),
    new QD_Knob(1, "Previous", QD_KnobType.Input, 35, true) // Changed to true to allow multiple previous connections.
};
```

**Comment by Vahv1** [comment]
Ah, thanks a lot! No idea how I missed that.

**Comment by QuantumTekSupport** [comment]
Glad I could help!
